services:
  politician-tracker:
    build: .
    container_name: politician-tracker
    restart: unless-stopped
    ports:
      - "8085:8000"
    volumes:
      - db-data:/app/data

volumes:
  db-data:
    driver: local
